import { useEffect, useState } from "react";
import ParentService from "../../services/parentService";

export default function ParentDashboard() {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { ParentService.getMyFinance().then(setData).catch(() => setError("Unable to load your children’s finance records.")); }, []);
  if (error) return <div className="p-8 text-rose-600">{error}</div>;
  if (!data) return <div className="p-8 text-slate-500">Loading parent finance records...</div>;
  return <main className="min-h-screen bg-slate-50 p-5 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-3xl font-bold text-slate-900">My Children’s Fees</h1><p className="mt-1 text-slate-500">Read-only expected fees, payments, receipts, and balances.</p></div>{data.children.map((child: any) => <section key={child.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">{child.firstName} {child.lastName}</h2><p className="text-sm text-slate-500">{child.admissionNumber} · {child.schoolClass?.name ?? "No class"}</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Expected", child.financeSummary.expected], ["Paid", child.financeSummary.paid], ["Balance", child.financeSummary.balance]].map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold">UGX {Number(value).toLocaleString()}</p></div>)}</div><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-3 py-2">Date</th><th className="px-3 py-2">Receipt</th><th className="px-3 py-2">Amount</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Proof</th></tr></thead><tbody>{child.payments.map((payment: any) => <tr key={payment.id} className="border-t"><td className="px-3 py-2">{new Date(payment.date).toLocaleDateString()}</td><td className="px-3 py-2">{payment.receiptNumber ?? "—"}</td><td className="px-3 py-2">UGX {payment.amount.toLocaleString()}</td><td className="px-3 py-2">{payment.status}</td><td className="px-3 py-2">{payment.proofUrl ? <a href={payment.proofUrl} target="_blank" rel="noreferrer" className="text-blue-700 underline">View</a> : "—"}</td></tr>)}</tbody></table></div></section>)}</div></main>;
}
