import { useMemo, useState } from 'react';
import ChildTabs from './ChildTabs';
import { useParentDashboard } from './ParentDashboardContext';
import PaymentProofViewer from '../director/finance/payments/PaymentProofViewer';

const money = (value: number) => `UGX ${value.toLocaleString()}`;

export default function ParentFinance() {
  const { data, loading, error } = useParentDashboard(); const [year, setYear] = useState(''); const [term, setTerm] = useState(''); const [selectedProof, setSelectedProof] = useState<{ url: string; fileName?: string | null } | null>(null);
  const charges = data?.student?.finance.charges ?? [];
  const years = useMemo(() => Array.from(new Set(charges.map((charge) => charge.academicYear).filter(Boolean))) as string[], [charges]);
  const terms = useMemo(() => Array.from(new Set(charges.filter((charge) => !year || charge.academicYear === year).map((charge) => charge.term).filter(Boolean))) as string[], [charges, year]);
  const filteredCharges = charges.filter((charge) => (!year || charge.academicYear === year) && (!term || charge.term === term));
  const totals = filteredCharges.reduce((sum, charge) => ({ expected: sum.expected + charge.expectedAmount, paid: sum.paid + charge.paidAmount, waived: sum.waived + charge.waivedAmount, balance: sum.balance + charge.balance }), { expected: 0, paid: 0, waived: 0, balance: 0 });
  if (loading) return <p className="text-slate-600">Loading finance details…</p>;
  if (error || !data) return <p className="rounded-2xl bg-red-50 p-4 text-red-700">{error || 'No parent data is available.'}</p>;
  const student = data.student;
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Finance</h1><p className="mt-2 text-sm text-slate-500">Read-only fee accounts, balances, payment history and receipts for each child.</p></div><ChildTabs />
    {student ? <><section className="flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div className="h-16 w-16 overflow-hidden rounded-full bg-slate-200">{student.profile.passportPhoto ? <img src={student.profile.passportPhoto} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center font-bold text-slate-500">{student.profile.firstName[0]}</div>}</div><div><h2 className="text-xl font-semibold">{student.profile.firstName} {student.profile.lastName}</h2><p className="text-sm text-slate-500">{student.profile.admissionNumber} · {student.profile.className || 'No class'}</p></div><div className="grid flex-1 gap-2 sm:ml-auto sm:max-w-md sm:grid-cols-2"><select value={year} onChange={(event) => { setYear(event.target.value); setTerm(''); }} className="rounded-xl border px-3 py-2"><option value="">All academic years</option>{years.map((item) => <option key={item}>{item}</option>)}</select><select value={term} onChange={(event) => setTerm(event.target.value)} className="rounded-xl border px-3 py-2"><option value="">All terms</option>{terms.map((item) => <option key={item}>{item}</option>)}</select></div></section>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Expected" value={totals.expected} /><Card label="Paid" value={totals.paid} positive /><Card label="Waived" value={totals.waived} /><Card label="Balance" value={totals.balance} warning /></section>
      <section className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><h2 className="text-xl font-semibold">Fee breakdown</h2><p className="mt-1 text-sm text-slate-500">Expected, paid and balance by fee category.</p></div><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Fee category</th><th className="p-4">Year</th><th className="p-4">Term</th><th className="p-4 text-right">Expected</th><th className="p-4 text-right">Paid</th><th className="p-4 text-right">Waived</th><th className="p-4 text-right">Balance</th><th className="p-4">Status</th></tr></thead><tbody>{filteredCharges.length === 0 ? <tr><td colSpan={8} className="p-8 text-center text-slate-500">No fee charges match these filters.</td></tr> : filteredCharges.map((charge) => <tr key={charge.id} className="border-t"><td className="p-4 font-semibold">{charge.feeType}</td><td className="p-4">{charge.academicYear || '—'}</td><td className="p-4">{charge.term || '—'}</td><td className="p-4 text-right">{money(charge.expectedAmount)}</td><td className="p-4 text-right">{money(charge.paidAmount)}</td><td className="p-4 text-right">{money(charge.waivedAmount)}</td><td className="p-4 text-right font-semibold">{money(charge.balance)}</td><td className="p-4"><Badge value={charge.status} /></td></tr>)}</tbody><tfoot className="bg-slate-50 font-bold"><tr><td className="p-4" colSpan={3}>Total</td><td className="p-4 text-right">{money(totals.expected)}</td><td className="p-4 text-right">{money(totals.paid)}</td><td className="p-4 text-right">{money(totals.waived)}</td><td className="p-4 text-right">{money(totals.balance)}</td><td /></tr></tfoot></table></section>
      {selectedProof && <div className="relative"><button type="button" onClick={() => setSelectedProof(null)} className="absolute right-4 top-4 z-10 rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Close preview</button><PaymentProofViewer url={selectedProof.url} fileName={selectedProof.fileName} /></div>}
      <section className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><h2 className="text-xl font-semibold">Payment history</h2><p className="mt-1 text-sm text-slate-500">Approved, rejected and reversed transactions remain visible for transparency.</p></div><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Date</th><th className="p-4">Fee</th><th className="p-4">Receipt</th><th className="p-4">Method</th><th className="p-4 text-right">Amount</th><th className="p-4">Status</th><th className="p-4">Proof</th></tr></thead><tbody>{student.finance.payments.length === 0 ? <tr><td colSpan={7} className="p-8 text-center text-slate-500">No payment records available.</td></tr> : student.finance.payments.map((payment) => <tr key={payment.id} className="border-t"><td className="p-4">{payment.date ? new Date(payment.date).toLocaleString() : '—'}</td><td className="p-4">{payment.feeType || payment.description || 'Payment'}</td><td className="p-4">{payment.receiptNumber || '—'}</td><td className="p-4">{payment.method || '—'}</td><td className="p-4 text-right font-semibold">{money(payment.amount)}</td><td className="p-4"><Badge value={payment.status || 'Unknown'} /></td><td className="p-4">{payment.proofUrl ? <button type="button" onClick={() => setSelectedProof({ url: payment.proofUrl!, fileName: payment.proofFileName })} className="font-semibold text-blue-700">View proof</button> : '—'}</td></tr>)}</tbody></table></section></> : <p className="rounded-3xl border bg-white p-6 text-slate-500">Select a child to view their financial account.</p>}
  </div>;
}

function Card({ label, value, positive, warning }: { label: string; value: number; positive?: boolean; warning?: boolean }) { return <div className={`rounded-3xl border p-5 shadow-sm ${warning ? 'border-amber-200 bg-amber-50' : positive ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-white'}`}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{money(value)}</p></div>; }
function Badge({ value }: { value: string }) { const status = value.toUpperCase(); const good = ['FULLY_PAID','COMPLETED','APPROVED'].includes(status); const bad = ['REVERSED','REJECTED','NOT_PAID'].includes(status); return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${good ? 'bg-emerald-100 text-emerald-800' : bad ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800'}`}>{value.replaceAll('_', ' ')}</span>; }
