import { useState, type FormEvent } from 'react';
import { Eye, EyeOff, KeyRound, X } from 'lucide-react';
import AuthService from '../../services/authService';
import { useParentDashboard } from './ParentDashboardContext';

function errorMessage(error: unknown) { const response = error as { response?: { data?: { message?: string | string[] } } }; const message = response.response?.data?.message; return Array.isArray(message) ? message.join(' ') : message || 'Unable to change password.'; }

export default function ParentSettings() {
  const { data, loading, error } = useParentDashboard();
  const [showPasswordForm, setShowPasswordForm] = useState(false); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [message, setMessage] = useState(''); const [formError, setFormError] = useState(''); const [saving, setSaving] = useState(false);
  const closeForm = () => { setShowPasswordForm(false); setCurrentPassword(''); setNewPassword(''); setConfirmPassword(''); setFormError(''); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); setFormError(''); if (newPassword.length < 8) { setFormError('The new password must contain at least 8 characters.'); return; } if (newPassword !== confirmPassword) { setFormError('The new passwords do not match.'); return; } setSaving(true); try { const result = await AuthService.changePassword(currentPassword, newPassword); setMessage(result.message); closeForm(); } catch (reason) { setFormError(errorMessage(reason)); } finally { setSaving(false); } };
  if (loading) return <p className="text-slate-500">Loading account settings…</p>;
  if (error || !data) return <p className="rounded-2xl bg-red-50 p-4 text-red-700">{error || 'No parent account is available.'}</p>;
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Settings</h1><p className="mt-2 text-sm text-slate-500">Review your school-recorded information and manage portal security.</p></div>
    {message && <p className="rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</p>}
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="h-20 w-20 overflow-hidden rounded-full bg-slate-200">{data.parent.profilePhoto ? <img src={data.parent.profilePhoto} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-2xl font-bold text-slate-500">{data.parent.firstName[0]}</div>}</div><div><h2 className="text-xl font-semibold">{data.parent.firstName} {data.parent.lastName}</h2><p className="text-sm text-slate-500">Parent/guardian record</p></div></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Phone" value={data.parent.phone || 'Not provided'} /><Info label="Communication email" value={data.parent.email || 'Not provided'} /><Info label="Occupation" value={data.parent.occupation || 'Not provided'} /><Info label="Address" value={data.parent.address || 'Not provided'} /></dl><p className="mt-6 rounded-2xl bg-blue-50 p-4 text-sm text-blue-800">Guardian details are maintained by the school. Contact the administration if anything needs correction.</p></section>
      <section className="self-start rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">Portal security</h2><p className="mt-2 text-sm text-slate-500">Choose a private password you can remember and never share it.</p></div><KeyRound className="shrink-0 text-blue-600" /></div>{!showPasswordForm ? <button type="button" onClick={() => { setMessage(''); setShowPasswordForm(true); }} className="mt-6 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">Change portal password</button> : <form onSubmit={submit} className="mt-6 space-y-4 rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Change password</h3><button type="button" onClick={closeForm} className="rounded-lg p-2 text-slate-500 hover:bg-white" aria-label="Close password form"><X size={18} /></button></div>{formError && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{formError}</p>}<Password label="Current password" value={currentPassword} onChange={setCurrentPassword} /><Password label="New password" value={newPassword} onChange={setNewPassword} minimum /><Password label="Confirm new password" value={confirmPassword} onChange={setConfirmPassword} minimum /><div className="flex gap-3"><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Updating…' : 'Update password'}</button><button type="button" onClick={closeForm} className="rounded-xl border bg-white px-5 py-3 text-sm font-semibold">Cancel</button></div></form>}</section></div>
  </div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-50 p-4"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
function Password({ label, value, onChange, minimum }: { label: string; value: string; onChange: (value: string) => void; minimum?: boolean }) { const [visible, setVisible] = useState(false); return <label className="block text-sm font-medium text-slate-700">{label}<span className="relative mt-2 block"><input required minLength={minimum ? 8 : undefined} type={visible ? 'text' : 'password'} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border bg-white px-4 py-3 pr-12" /><button type="button" onClick={() => setVisible((current) => !current)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500" aria-label={visible ? `Hide ${label.toLowerCase()}` : `Show ${label.toLowerCase()}`}>{visible ? <EyeOff size={19} /> : <Eye size={19} />}</button></span></label>; }
