import { DateTime } from "luxon";
import type { PaymentFilters as Filters, PaymentOptions } from "../../../../services/paymentService";

type Props = { value: Filters; options: PaymentOptions | null; onChange: (filters: Filters) => void };
const methods = ["CASH", "MOBILE_MONEY", "BANK_DEPOSIT", "BANK_TRANSFER", "CHEQUE", "CARD", "OTHER"];
const statuses = ["COMPLETED", "REVERSED", "DRAFT", "REJECTED", "CANCELLED"];

export default function PaymentFilters({ value, options, onChange }: Props) {
  const set = (key: keyof Filters, next: string | number | undefined) => onChange({ ...value, [key]: next || undefined, page: 1 });
  const period = (kind: "today" | "week" | "month" | "year" | "all") => { const now = DateTime.now().setZone("Africa/Kampala"); const start = kind === "week" ? now.startOf("week") : kind === "month" ? now.startOf("month") : kind === "year" ? now.startOf("year") : now; const end = kind === "week" ? now.endOf("week") : kind === "month" ? now.endOf("month") : kind === "year" ? now.endOf("year") : now; onChange({ ...value, startDate: kind === "all" ? undefined : start.toISODate() ?? undefined, endDate: kind === "all" ? undefined : end.toISODate() ?? undefined, page: 1 }); };
  const terms = options?.terms.filter((term) => !value.academicYearId || term.academicYearId === value.academicYearId) ?? [];
  const inputClass = "rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm";
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => period("today")} className="rounded-full border px-3 py-1.5 text-xs font-semibold">Today</button><button type="button" onClick={() => period("week")} className="rounded-full border px-3 py-1.5 text-xs font-semibold">This week</button><button type="button" onClick={() => period("month")} className="rounded-full border px-3 py-1.5 text-xs font-semibold">This month</button><button type="button" onClick={() => period("year")} className="rounded-full border px-3 py-1.5 text-xs font-semibold">This year</button><button type="button" onClick={() => period("all")} className="rounded-full border px-3 py-1.5 text-xs font-semibold">All payments</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
    <input type="search" value={value.search ?? ""} onChange={(event) => set("search", event.target.value)} placeholder="Student, receipt or reference" className={`${inputClass} sm:col-span-2`}/><input type="date" value={value.startDate ?? ""} onChange={(event) => set("startDate", event.target.value)} className={inputClass}/><input type="date" value={value.endDate ?? ""} onChange={(event) => set("endDate", event.target.value)} className={inputClass}/>
    <select value={value.academicYearId ?? ""} onChange={(event) => onChange({ ...value, academicYearId: event.target.value || undefined, termId: undefined, page: 1 })} className={inputClass}><option value="">All academic years</option>{options?.academicYears.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={value.termId ?? ""} onChange={(event) => set("termId", event.target.value)} className={inputClass}><option value="">All terms</option>{terms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={value.classId ?? ""} onChange={(event) => set("classId", event.target.value)} className={inputClass}><option value="">All classes</option>{options?.classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={value.studentCategoryId ?? ""} onChange={(event) => set("studentCategoryId", event.target.value)} className={inputClass}><option value="">All categories</option>{options?.studentCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
    <select value={value.feeTypeId ?? ""} onChange={(event) => set("feeTypeId", event.target.value)} className={inputClass}><option value="">All fee types</option>{options?.feeTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={value.method ?? ""} onChange={(event) => set("method", event.target.value)} className={inputClass}><option value="">All methods</option>{methods.map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select><select value={value.status ?? ""} onChange={(event) => set("status", event.target.value)} className={inputClass}><option value="">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select><select value={value.recordedByUserId ?? ""} onChange={(event) => set("recordedByUserId", event.target.value)} className={inputClass}><option value="">All recorded-by users</option>{options?.recordedByUsers.map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</select>
  </div></section>;
}
