import type { FinancePayment } from "../../../../services/paymentService";
import { formatKampalaDateTime } from "../../../../utils/kampalaDateTime";

const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);

export default function ReceiptPreview({ payment }: { payment: FinancePayment }) {
  const structure = payment.studentCharge?.financeStructure;
  const fee = structure?.feeType?.name ?? payment.feeType?.name ?? "Unallocated fee";
  const period = `${structure?.academicYear?.name ?? "Unknown year"}, ${structure?.term?.name ?? "Unknown term"}`;
  const studentName = payment.student ? `${payment.student.firstName} ${payment.student.lastName}` : payment.studentId;
  const printReceipt = () => {
    const printWindow = window.open("", "_blank", "width=760,height=850");
    if (!printWindow) return;
    printWindow.document.write(`<!doctype html><html><head><title>${escapeHtml(payment.receiptNumber ?? "Payment receipt")}</title><style>body{font-family:Arial,sans-serif;color:#0f172a;margin:0;padding:36px}.receipt{max-width:680px;margin:auto;border:1px solid #cbd5e1;border-radius:16px;padding:28px}h1{font-size:24px;margin:0}.school{font-size:14px;color:#475569;margin-top:6px}.number{margin:24px 0;padding:14px;background:#f1f5f9;border-radius:10px;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px 24px}.item span{display:block;font-size:11px;text-transform:uppercase;color:#64748b;margin-bottom:4px}.amount{font-size:25px;font-weight:700}.footer{margin-top:30px;padding-top:16px;border-top:1px solid #cbd5e1;font-size:12px;color:#64748b}@media print{body{padding:0}.receipt{border:none}}</style></head><body><main class="receipt"><h1>Mpumudde High School</h1><p class="school">Official student payment receipt</p><div class="number">Receipt: ${escapeHtml(payment.receiptNumber ?? "Legacy payment")}</div><div class="grid"><div class="item"><span>Student</span><b>${escapeHtml(studentName)}</b></div><div class="item"><span>Admission number</span><b>${escapeHtml(payment.student?.admissionNumber)}</b></div><div class="item"><span>Fee type</span><b>${escapeHtml(fee)}</b></div><div class="item"><span>Academic period</span><b>${escapeHtml(period)}</b></div><div class="item"><span>Class / category</span><b>${escapeHtml(`${structure?.schoolClass?.name ?? "—"} / ${structure?.studentCategory?.name ?? "—"}`)}</b></div><div class="item"><span>Payment method</span><b>${escapeHtml(payment.method.replaceAll("_", " "))}</b></div><div class="item"><span>Date and time (EAT)</span><b>${escapeHtml(formatKampalaDateTime(payment.date))}</b></div><div class="item"><span>Transaction reference</span><b>${escapeHtml(payment.transactionReference)}</b></div><div class="item"><span>Amount received</span><div class="amount">UGX ${escapeHtml(payment.amount.toLocaleString())}</div></div><div class="item"><span>Recorded by</span><b>${escapeHtml(payment.recordedBy?.email ?? "School finance office")}</b></div></div><p class="footer">Generated from the Mpumudde High School finance system. Payment status: ${escapeHtml(payment.status)}.</p></main><script>window.onload=()=>{window.print();window.onafterprint=()=>window.close();}</script></body></html>`);
    printWindow.document.close();
  };
  return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Receipt</p><p className="mt-1 text-lg font-semibold text-slate-900">{payment.receiptNumber ?? "Legacy payment"}</p><p className="mt-2 text-sm text-slate-600">UGX {payment.amount.toLocaleString()} received for <b>{fee}</b> ({period}) on {formatKampalaDateTime(payment.date)} EAT.</p><button type="button" onClick={printReceipt} className="mt-3 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700">Print receipt only</button></div>;
}
