import { useState } from "react";
import PayrollService, { type PayrollTeacher } from "../../../../../services/payrollService";

export default function SalarySettings({ teachers, onSaved }: { teachers: PayrollTeacher[]; onSaved: () => void }) {
  const [teacherId, setTeacherId] = useState(""); const [salary, setSalary] = useState(""); const [frequency, setFrequency] = useState("MONTHLY"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const select = (id: string) => { setTeacherId(id); const teacher = teachers.find((item) => item.id === id); setSalary(String(teacher?.employment?.salary ?? "")); setFrequency(teacher?.employment?.payFrequency ?? "MONTHLY"); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const teacher = teachers.find((item) => item.id === teacherId); if (!teacher) return; setSaving(true); setMessage(""); try { await PayrollService.updateSalary(teacher, Number(salary), frequency); setMessage("Salary details updated."); onSaved(); } catch { setMessage("Unable to update salary details."); } finally { setSaving(false); } };
  return <form onSubmit={save} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-900">Teacher salary settings</h2><p className="mt-1 text-sm text-slate-500">Update the agreed basic salary and payment frequency before generating payroll.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><select required value={teacherId} onChange={(event) => select(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2"><option value="">Select teacher</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.firstName} {teacher.lastName} — {teacher.employment?.employeeNumber}</option>)}</select><input required type="number" min="0" value={salary} onChange={(event) => setSalary(event.target.value)} placeholder="Basic salary (UGX)" className="rounded-xl border border-slate-200 px-3 py-2"/><select value={frequency} onChange={(event) => setFrequency(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2"><option value="MONTHLY">Monthly</option><option value="BI_WEEKLY">Bi-weekly</option><option value="WEEKLY">Weekly</option><option value="TERM">Per term</option></select></div>{message && <p className="mt-3 text-sm text-slate-600">{message}</p>}<button disabled={saving} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save salary settings"}</button></form>;
}
