import type { StudentAccountDetails } from "../../../../services/studentAccountService";
import { formatKampalaDateTime } from "../../../../utils/kampalaDateTime";

const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
const money = (value: number) => `UGX ${value.toLocaleString()}`;

export default function StudentStatement({ account }: { account: StudentAccountDetails }) {
  const print = () => {
    const target = window.open("", "_blank", "width=960,height=760");
    if (!target) return;
    const chargeRows = account.charges.map((charge) => `<tr><td>${escapeHtml(charge.financeStructure.feeType.name)}</td><td>${escapeHtml(charge.financeStructure.academicYear.name)} · ${escapeHtml(charge.financeStructure.term.name)}</td><td>${money(charge.expectedAmount)}</td><td>${money(charge.paidAmount)}</td><td>${money(charge.waivedAmount)}</td><td>${money(charge.expectedAmount - charge.paidAmount - charge.waivedAmount)}</td></tr>`).join("");
    const paymentRows = account.payments.map((payment) => `<tr><td>${escapeHtml(formatKampalaDateTime(payment.date))}</td><td>${escapeHtml(payment.receiptNumber)}</td><td>${escapeHtml(payment.feeType?.name)}</td><td>${escapeHtml(payment.method.replaceAll("_", " "))}</td><td>${escapeHtml(payment.status)}</td><td>${money(payment.amount)}</td></tr>`).join("");
    target.document.write(`<!doctype html><html><head><title>Student Financial Statement</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:36px}header{display:flex;justify-content:space-between;border-bottom:2px solid #172033;padding-bottom:18px}.muted{color:#64748b}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.card{border:1px solid #dbe2ea;border-radius:10px;padding:12px}.card b{display:block;margin-top:6px}h2{margin-top:28px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border-bottom:1px solid #e2e8f0;padding:9px;text-align:left}th{background:#f8fafc}.right{text-align:right}@media print{body{margin:12mm}}</style></head><body><header><div><h1>Mpumudde High School</h1><p class="muted">Student Financial Statement</p></div><div class="right"><b>${escapeHtml(account.student.firstName)} ${escapeHtml(account.student.lastName)}</b><p>${escapeHtml(account.student.admissionNumber)}</p><p>${escapeHtml(account.student.schoolClass?.name)}</p></div></header><p class="muted">Generated ${escapeHtml(new Date().toLocaleString())}</p><section class="summary"><div class="card">Expected<b>${money(account.summary.expectedAmount)}</b></div><div class="card">Paid<b>${money(account.summary.paidAmount)}</b></div><div class="card">Waived<b>${money(account.summary.waivedAmount)}</b></div><div class="card">Outstanding<b>${money(account.summary.outstandingBalance)}</b></div></section><h2>Fee charges</h2><table><thead><tr><th>Fee</th><th>Period</th><th>Expected</th><th>Paid</th><th>Waived</th><th>Balance</th></tr></thead><tbody>${chargeRows || '<tr><td colspan="6">No charges.</td></tr>'}</tbody></table><h2>Payment history</h2><table><thead><tr><th>Date</th><th>Receipt</th><th>Fee</th><th>Method</th><th>Status</th><th>Amount</th></tr></thead><tbody>${paymentRows || '<tr><td colspan="6">No payments.</td></tr>'}</tbody></table></body></html>`);
    target.document.close(); target.focus(); target.print();
  };
  return <button type="button" onClick={print} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">Print complete statement</button>;
}
