import { useEffect, useState } from "react";
import ExpenseService from "../../../../services/expenseService";
import OtherIncomeService, { type OtherIncome } from "../../../../services/otherIncomeService";

export default function OtherIncomePanel({ canCreate, onCreated }: { canCreate: boolean; onCreated: () => void }) {
  const [records, setRecords] = useState<OtherIncome[]>([]); const [category, setCategory] = useState("DONATION"); const [amount, setAmount] = useState(""); const [source, setSource] = useState(""); const [method, setMethod] = useState("CASH"); const [date, setDate] = useState(new Date().toISOString().slice(0, 16)); const [reference, setReference] = useState(""); const [proof, setProof] = useState<File | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = () => void OtherIncomeService.list().then(setRecords).catch(() => setMessage("Unable to load other income records.")); useEffect(load, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { const uploaded = proof ? await ExpenseService.uploadProof(proof) : undefined; await OtherIncomeService.create({ category, amount: Number(amount), source, method, incomeDate: date ? new Date(date).toISOString() : undefined, referenceNumber: reference || undefined, proofUrl: uploaded?.url, proofFileName: proof?.name }); setAmount(""); setSource(""); setReference(""); setProof(null); setMessage("Other income recorded."); load(); onCreated(); } catch { setMessage("Unable to record other income."); } finally { setSaving(false); } };
  const field = "rounded-xl border border-slate-200 px-3 py-2 text-sm";
  return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div><h3 className="font-semibold text-slate-900">Other school income</h3><p className="mt-1 text-sm text-slate-500">Donations, grants, rentals, fundraising, and other non-student income.</p></div>{canCreate && <form onSubmit={submit} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select value={category} onChange={(event) => setCategory(event.target.value)} className={field}><option value="DONATION">Donation</option><option value="GRANT">Grant</option><option value="FACILITY_RENTAL">Facility rental</option><option value="FUNDRAISING">Fundraising</option><option value="OTHER">Other</option></select><input required value={source} onChange={(event) => setSource(event.target.value)} placeholder="Source or payer" className={field}/><input required type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Amount (UGX)" className={field}/><select value={method} onChange={(event) => setMethod(event.target.value)} className={field}><option value="CASH">Cash</option><option value="MOBILE_MONEY">Mobile Money</option><option value="BANK_TRANSFER">Bank Transfer</option><option value="CHEQUE">Cheque</option><option value="OTHER">Other</option></select><input type="datetime-local" value={date} onChange={(event) => setDate(event.target.value)} className={field}/><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Reference (optional)" className={field}/><input type="file" accept="image/*,.pdf" onChange={(event) => setProof(event.target.files?.[0] ?? null)} className="text-sm"/><button disabled={saving} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Recording..." : "Record income"}</button></form>}{message && <p className="mt-3 text-sm text-slate-600">{message}</p>}<div className="mt-5 space-y-2">{records.slice(0, 5).map((record) => <div key={record.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-3 text-sm"><span><b>{record.source}</b> · {record.category.replaceAll("_", " ")}<span className="block text-xs text-slate-500">{new Date(record.incomeDate).toLocaleString()} · {record.recordedBy?.email ?? "System"}</span></span><span className="font-semibold text-emerald-700">UGX {record.amount.toLocaleString()}</span></div>)}{records.length === 0 && <p className="text-sm text-slate-500">No other income recorded.</p>}</div></section>;
}
