import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Plus } from "lucide-react";
import { useAuth } from "../../../../context/AuthContext";
import FeeTypeService, { type FinanceFeeType } from "../../../../services/feeTypeService";
import PaymentModal from "../payments/PaymentModal";
import FeeTypeForm from "./FeeTypeForm";
import FeeTypesTable from "./FeeTypesTable";

export default function FeeTypes() {
  const { hasPermission, hasRole } = useAuth();
  const canManage = hasRole("SUPER_ADMIN") || hasPermission("finance.fee-structures.manage");
  const [items, setItems] = useState<FinanceFeeType[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [editing, setEditing] = useState<FinanceFeeType | null | undefined>(undefined); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { setItems(await FeeTypeService.list()); } catch { setError("Unable to load fee types."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) && (!status || String(item.isActive) === status)), [items, search, status]);
  const save = async (values: { name: string; isActive: boolean }) => { setSaving(true); setError(null); try { const saved = editing ? await FeeTypeService.update(editing.id, values) : await FeeTypeService.create(values); setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setEditing(undefined); setMessage(editing ? "Fee type updated." : "Fee type added."); } catch (reason) { const backend = axios.isAxiosError(reason) ? reason.response?.data?.message : undefined; setError(Array.isArray(backend) ? backend.join(" ") : backend || "Unable to save fee type."); } finally { setSaving(false); } };
  const toggle = async (item: FinanceFeeType) => { try { const saved = await FeeTypeService.update(item.id, { isActive: !item.isActive }); setItems((current) => current.map((value) => value.id === saved.id ? saved : value)); } catch { setError("Unable to change fee type status."); } };
  const remove = async (item: FinanceFeeType) => { if (!window.confirm(`Delete unused fee type ${item.name}?`)) return; try { await FeeTypeService.delete(item.id); setItems((current) => current.filter((value) => value.id !== item.id)); } catch { setError("Used fee types cannot be deleted. Deactivate the fee type instead."); } };
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Fee Types</h2><p className="mt-1 text-sm text-slate-500">Manage reusable fee names such as Registration, Tuition, Reams, and Development.</p></div>{canManage && <button type="button" onClick={() => setEditing(null)} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/>Add fee type</button>}</div>{message && <p className="rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error && <p className="rounded-2xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 sm:grid-cols-[1fr_14rem]"><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search fee types" className="rounded-xl border border-slate-200 px-4 py-3"/><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-200 px-4 py-3"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div><FeeTypesTable items={filtered} loading={loading} canManage={canManage} onEdit={setEditing} onToggle={(item) => void toggle(item)} onDelete={(item) => void remove(item)}/>{editing !== undefined && <PaymentModal title={editing ? "Edit fee type" : "Add fee type"} onClose={() => setEditing(undefined)} width="max-w-xl"><FeeTypeForm feeType={editing} saving={saving} onSubmit={save} onCancel={() => setEditing(undefined)}/></PaymentModal>}</div>;
}
