import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, Clock3, MapPin, Share2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { formatNewsDateTime } from "../../../newsroom/format";
import { newsroomCategoryLabels, type NewsroomItem } from "../../../newsroom/types";
import { newsroomService } from "../../../services/newsroomService";
import NewsroomShell from "./NewsroomShell";

export default function ArticlePage() {
  const { slug = "" } = useParams(); const [item, setItem] = useState<NewsroomItem | null | undefined>(undefined);
  useEffect(() => { let active = true; void newsroomService.getBySlug(slug).then(next => { if (active) setItem(next); }); return () => { active = false; }; }, [slug]);
  if (item === undefined) return <NewsroomShell><main className="site-container py-24 text-center text-slate-500">Loading story…</main></NewsroomShell>;
  if (!item) return <NewsroomShell><main className="site-container py-24 text-center"><h1 className="text-3xl font-black text-slate-950 dark:text-white">Story not found</h1><Link to="/newsroom" className="mt-5 inline-flex text-[var(--brand-green)] font-black">Return to Newsroom</Link></main></NewsroomShell>;
  const share = async () => { if (navigator.share) await navigator.share({ title: item.title, text: item.excerpt, url: window.location.href }); else await navigator.clipboard.writeText(window.location.href); };
  return <NewsroomShell><main><article><header className="site-container max-w-5xl py-12 sm:py-16"><Link to={`/newsroom/${item.category}`} className="inline-flex items-center gap-2 text-sm font-black text-[var(--brand-green)]"><ArrowLeft size={17} />Back to {newsroomCategoryLabels[item.category]}</Link><div className="mt-8 flex flex-wrap items-center gap-3 text-xs font-black"><span className="rounded-full bg-emerald-50 px-3 py-2 text-emerald-800 dark:bg-emerald-400/10 dark:text-emerald-200">{newsroomCategoryLabels[item.category]}</span>{item.priority && <span className="rounded-full bg-amber-50 px-3 py-2 uppercase text-amber-800 dark:bg-amber-400/10 dark:text-amber-200">{item.priority}</span>}</div><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.08] tracking-tight text-slate-950 dark:text-white sm:text-6xl">{item.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{item.excerpt}</p><div className="mt-7 flex flex-wrap items-center gap-5 text-sm text-slate-500 dark:text-slate-400"><span>{item.author}</span><span>{formatNewsDateTime(item.publishedAt)}</span><span>{item.readMinutes} min read</span><button onClick={() => void share()} className="inline-flex items-center gap-2 font-black text-[var(--brand-green)]"><Share2 size={16} />Share</button></div></header><div className="site-container max-w-6xl"><img src={item.image} alt={item.imageAlt} className="max-h-[38rem] w-full rounded-[2rem] object-cover" /></div><div className="site-container grid max-w-5xl gap-10 py-12 lg:grid-cols-[1fr_16rem]"><div className="space-y-6">{item.body.map((paragraph, index) => <p key={index} className="text-lg leading-9 text-slate-700 dark:text-slate-200">{paragraph}</p>)}</div><aside><div className="rounded-2xl bg-slate-100 p-5 dark:bg-white/5"><h2 className="font-black text-slate-950 dark:text-white">Story details</h2>{item.type === "event" && <div className="mt-4 space-y-3 text-sm text-slate-600 dark:text-slate-300"><p className="flex gap-2"><CalendarDays size={17} />{item.eventDate}</p><p className="flex gap-2"><Clock3 size={17} />{item.eventTime}</p><p className="flex gap-2"><MapPin size={17} />{item.eventLocation}</p></div>}<div className="mt-5 flex flex-wrap gap-2">{item.tags.map(tag => <span key={tag} className="rounded-full bg-white px-3 py-1.5 text-xs font-bold text-slate-600 dark:bg-white/10 dark:text-slate-300">{tag}</span>)}</div></div></aside></div></article></main></NewsroomShell>;
}
