import { type FormEvent, useMemo } from "react";
import { Search } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { newsroomCategoryLabels, type NewsroomCategory } from "../../../newsroom/types";
import { useNewsroom } from "../../../newsroom/useNewsroom";
import NewsroomCard from "./NewsroomCard";
import NewsroomShell from "./NewsroomShell";

const categories = Object.entries(newsroomCategoryLabels) as Array<[NewsroomCategory, string]>;

export default function SearchPage() {
  const [params, setParams] = useSearchParams();
  const search = params.get("q") || ""; const category = params.get("category") as NewsroomCategory | null; const year = params.get("year") || ""; const month = params.get("month") || "";
  const query = useMemo(() => ({ search, category: category || undefined, year: year || undefined, month: month || undefined, pageSize: 50 }), [search, category, year, month]);
  const { result, loading } = useNewsroom(query);
  const update = (name: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); setParams(next); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); update("q", String(data.get("q") || "")); };
  return <NewsroomShell><main className="site-container py-12 sm:py-16"><header className="max-w-3xl"><p className="section-badge">Archive & search</p><h1 className="section-title">Find a Newsroom story</h1><p className="section-lead">Search headlines, summaries, authors and topics, or narrow the archive by category and publication date.</p></header><div className="mt-9 rounded-[1.5rem] border border-slate-200 bg-slate-50 p-5 dark:border-white/10 dark:bg-white/[.035]"><form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search terms</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input name="q" defaultValue={search} placeholder="Search the Newsroom" className="w-full rounded-xl border border-slate-300 bg-white py-3 pl-11 pr-4 text-slate-900 outline-none focus:border-emerald-600 dark:border-white/10 dark:bg-white/5 dark:text-white" /></label><button className="public-primary-button justify-center">Search</button></form><div className="mt-4 grid gap-3 sm:grid-cols-3"><select value={category || ""} onChange={event => update("category", event.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-900 dark:text-white"><option value="">All categories</option>{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={year} onChange={event => update("year", event.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-900 dark:text-white"><option value="">All years</option><option value="2026">2026</option></select><select value={month} onChange={event => update("month", event.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-900 dark:text-white"><option value="">All months</option>{[["01","January"],["02","February"],["03","March"],["04","April"],["05","May"],["06","June"],["07","July"],["08","August"],["09","September"],["10","October"],["11","November"],["12","December"]].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></div></div>{loading ? <p className="py-20 text-center text-slate-500">Searching…</p> : <><p className="mt-10 text-sm font-bold text-slate-500">{result.total} {result.total === 1 ? "result" : "results"}</p><div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{result.items.map(item => <NewsroomCard key={item.id} item={item} />)}</div>{result.total === 0 && <div className="mt-6 rounded-2xl bg-slate-100 p-10 text-center text-slate-600 dark:bg-white/5 dark:text-slate-300">No stories matched those filters. Try a broader search.</div>}</>}</main></NewsroomShell>;
}
