import { useEffect, useMemo, useState } from 'react';
import { Archive, Eye, Pencil, Plus, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import ParentService, { type Guardian } from '../../../services/parentService';

export default function GuardiansPage() {
  const [guardians, setGuardians] = useState<Guardian[]>([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all');
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { setGuardians(await ParentService.getGuardians()); setError(''); } catch { setError('Unable to load guardians.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => guardians.filter((guardian) => {
    const children = guardian.students.map((link) => `${link.student.firstName} ${link.student.lastName} ${link.student.admissionNumber} ${link.student.schoolClass?.name || ''}`).join(' ');
    const matchesSearch = `${guardian.firstName} ${guardian.lastName} ${guardian.phone ?? ''} ${guardian.email ?? ''} ${guardian.user?.email ?? ''} ${children}`.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = status === 'all' || (status === 'no-account' ? !guardian.user : status === 'active' ? guardian.user?.isActive : guardian.user && !guardian.user.isActive);
    return matchesSearch && matchesStatus;
  }), [guardians, search, status]);
  const archive = async (guardian: Guardian) => { if (!window.confirm(`Archive ${guardian.firstName} ${guardian.lastName}? Their portal will be disabled while school history is preserved.`)) return; try { await ParentService.deleteGuardian(guardian.id); await load(); } catch { setError('Unable to archive guardian.'); } };

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-bold">Guardians</h1><p className="mt-2 text-sm text-slate-500">Every active guardian is connected to at least one student.</p></div><Link to="/director/guardians/create" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white"><Plus size={18} />Register guardian</Link></div>
    <div className="grid gap-4 sm:grid-cols-3"><Summary label="Active guardians" value={guardians.length} /><Summary label="Portal accounts" value={guardians.filter((item) => item.user).length} /><Summary label="Without login" value={guardians.filter((item) => !item.user).length} /></div>
    <div className="flex flex-col gap-3 rounded-3xl border border-slate-200 bg-slate-50 p-4 md:flex-row"><label className="relative flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search guardian, child, class or admission number" className="w-full rounded-2xl border bg-white py-3 pl-11 pr-4" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-2xl border bg-white px-4 py-3"><option value="all">All account statuses</option><option value="active">Active portal</option><option value="inactive">Inactive portal</option><option value="no-account">No portal account</option></select></div>
    {error && <p className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}
    <div className="max-w-full overflow-x-auto rounded-3xl border border-slate-200 bg-white"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Guardian</th><th className="p-4">Contact</th><th className="p-4">Portal login</th><th className="p-4">Linked students</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-8 text-center text-slate-500">Loading guardians…</td></tr> : filtered.length === 0 ? <tr><td colSpan={6} className="p-8 text-center text-slate-500">No guardians match the current filters.</td></tr> : filtered.map((guardian) => <tr key={guardian.id} className="border-t border-slate-100 align-top"><td className="p-4"><div className="flex items-center gap-3"><div className="h-11 w-11 overflow-hidden rounded-full bg-slate-200">{guardian.profilePhoto ? <img src={guardian.profilePhoto} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center font-semibold text-slate-500">{guardian.firstName[0]}</div>}</div><p className="font-semibold text-slate-900">{guardian.firstName} {guardian.lastName}</p></div></td><td className="p-4"><p>{guardian.phone || '—'}</p><p className="text-xs text-slate-500">{guardian.email || 'No communication email'}</p></td><td className="p-4">{guardian.user ? <><p>{guardian.user.email}</p><p className="text-xs text-slate-500">Last login: {guardian.user.lastLogin ? new Date(guardian.user.lastLogin).toLocaleString() : 'Never'}</p></> : <span className="text-amber-700">Not created</span>}</td><td className="p-4"><div className="space-y-2">{guardian.students.map((link) => <div key={link.id}><p className="font-medium">{link.student.firstName} {link.student.lastName}{link.isPrimary ? ' · Primary' : ''}</p><p className="text-xs text-slate-500">{link.student.admissionNumber} · {link.student.schoolClass?.name || 'No class'} · {link.relationship || 'Guardian'}</p></div>)}</div></td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${!guardian.user ? 'bg-amber-100 text-amber-800' : guardian.user.isActive ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'}`}>{!guardian.user ? 'No account' : guardian.user.isActive ? 'Active' : 'Inactive'}</span></td><td className="p-4"><div className="flex justify-end gap-2"><Link title="View" to={`/director/guardians/${guardian.id}`} className="rounded-xl border p-2 text-slate-700"><Eye size={17} /></Link><Link title="Edit" to={`/director/guardians/${guardian.id}/edit`} className="rounded-xl border p-2 text-blue-700"><Pencil size={17} /></Link><button title="Archive" onClick={() => void archive(guardian)} className="rounded-xl border p-2 text-red-700"><Archive size={17} /></button></div></td></tr>)}</tbody></table></div>
  </div>;
}

function Summary({ label, value }: { label: string; value: number }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>; }
